# Generated by Django 5.2.2 on 2025-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(blank=True, help_text='Unique identifier for the medical record.', max_length=100, null=True, unique=True)),
                ('date_derniere_consultation', models.DateField(blank=True, help_text='Date of the last consultation recorded in this file.', null=True)),
                ('dernier_acces', models.DateTimeField(auto_now=True, help_text='Date and time of the last access/update to this medical record.')),
                ('pathologie_chronique', models.TextField(blank=True, help_text='Details of chronic pathologies (e.g., diabetes, hypertension).', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies (medications, food, environmental).', null=True)),
                ('antecedents_medicaux', models.TextField(blank=True, help_text='Past medical history, surgeries, major illnesses.', null=True)),
                ('vaccinations', models.TextField(blank=True, help_text='Record of vaccinations received.', null=True)),
            ],
            options={
                'verbose_name': 'Dossier Médical',
                'verbose_name_plural': 'Dossiers Médicaux',
                'ordering': ['patient__nom', 'patient__prenom'],
            },
        ),
    ]
