# Generated by Django 5.2.2 on 2025-06-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medical_Records', '0001_initial'),
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(help_text='The patient associated with this medical record.', on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='Patients.patient'),
        ),
    ]
