# Generated by Django 5.2.1 on 2025-06-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_Records', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossiermedical',
            options={'ordering': ['patient__nom'], 'verbose_name': 'Dossier Médical', 'verbose_name_plural': 'Dossiers Médicaux'},
        ),
    ]
