# Generated by Django 5.2.2 on 2025-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licence', models.CharField(help_text='Official medical license number.', max_length=100, unique=True)),
                ('specialite', models.CharField(help_text='Medical specialty (e.g., General Practitioner, Cardiologist).', max_length=100)),
                ('axe', models.CharField(blank=True, help_text='Specific area of focus or sub-specialty if applicable.', max_length=100, null=True)),
                ('lieu', models.CharField(blank=True, help_text='Primary workplace or affiliated institution.', max_length=100, null=True)),
                ('annee_exercice', models.IntegerField(blank=True, help_text='Year of professional practice commencement.', null=True)),
                ('email_pro', models.EmailField(blank=True, help_text="Professional email address (optional, can be different from user's main email).", max_length=254, null=True)),
                ('photo_profil', models.ImageField(blank=True, help_text='Profile photo of the medical personnel.', null=True, upload_to='medical_personnel_photos/')),
                ('telephone_pro', models.CharField(blank=True, help_text='Professional phone number.', max_length=20, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, help_text="Date and time of the last update to the medical personnel's profile.")),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date and time the medical personnel's profile was created.")),
            ],
            options={
                'verbose_name': 'Personnel Médical',
                'verbose_name_plural': 'Personnel Médical',
                'ordering': ['specialite', 'user__last_name'],
            },
        ),
    ]
