# Generated by Django 5.2.2 on 2025-06-05 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medical_Personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalpersonnel',
            name='user',
            field=models.OneToOneField(help_text='The user account associated with this medical personnel profile.', on_delete=django.db.models.deletion.CASCADE, related_name='medical_personnel_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
