# Generated by Django 5.2.1 on 2025-06-06 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_Personnel', '0002_initial'),
        ('Patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='comptePatientLie',
            field=models.OneToOneField(help_text='The user account associated with this medical personnel profile.', on_delete=django.db.models.deletion.CASCADE, related_name='medical_personnel_profile', to='Patients.patient'),
        ),
    ]
