# Generated by Django 5.2.2 on 2025-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_consultation', models.CharField(blank=True, help_text='Unique identifier for the consultation.', max_length=100, null=True, unique=True)),
                ('date_consultation', models.DateField(help_text='Date when the consultation took place.')),
                ('heure_debut', models.TimeField(help_text='Start time of the consultation.')),
                ('heure_fin', models.TimeField(blank=True, help_text='End time of the consultation.', null=True)),
                ('type_consultation', models.CharField(choices=[('ONLINE', 'En ligne'), ('IN_PERSON', 'En personne')], default='ONLINE', help_text='Type of consultation (online or in-person).', max_length=20)),
                ('compte_rendu', models.TextField(blank=True, help_text='Medical report or summary of the consultation.', null=True)),
                ('diagnostic', models.TextField(blank=True, help_text='Diagnosis made during the consultation.', null=True)),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Date and time of the last update to the consultation record.')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date and time the consultation record was created.')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_consultation', '-heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='DemandeConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(blank=True, help_text='Unique identifier for the consultation request.', max_length=100, null=True, unique=True)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée'), ('CANCELLED', 'Annulée')], default='PENDING', help_text='Current status of the consultation request.', max_length=20)),
                ('motif', models.TextField(help_text='Reason for the consultation request.')),
                ('date_demande', models.DateTimeField(auto_now_add=True, help_text='Date and time the consultation request was made.')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Date and time of the last update to the request status.')),
            ],
            options={
                'verbose_name': 'Demande de Consultation',
                'verbose_name_plural': 'Demandes de Consultations',
                'ordering': ['-date_demande'],
            },
        ),
    ]
