# Generated by Django 5.2.2 on 2025-06-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Consultations', '0001_initial'),
        ('Medical_Personnel', '0001_initial'),
        ('Medical_Records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='dossier_medical',
            field=models.ForeignKey(blank=True, help_text='The medical record associated with this consultation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_liees', to='Medical_Records.dossiermedical'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='medical_personnel',
            field=models.ForeignKey(blank=True, help_text='The medical personnel who conducted the consultation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_effectuees', to='Medical_Personnel.medicalpersonnel'),
        ),
    ]
