# Generated by Django 5.2.2 on 2025-06-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Consultations', '0002_initial'),
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(help_text='The patient who received the consultation.', on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Patients.patient'),
        ),
        migrations.AddField(
            model_name='demandeconsultation',
            name='patient',
            field=models.ForeignKey(help_text='The patient who initiated this consultation request.', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_consultation', to='Patients.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='demande_consultation',
            field=models.OneToOneField(blank=True, help_text='The original consultation request, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_reelle', to='Consultations.demandeconsultation'),
        ),
    ]
