# Generated by Django 5.2.2 on 2025-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Patient's last name.", max_length=100)),
                ('prenom', models.CharField(help_text="Patient's first name.", max_length=100)),
                ('date_naissance', models.DateField(help_text="Patient's date of birth.")),
                ('telephone', models.CharField(blank=True, help_text="Patient's phone number.", max_length=20, null=True)),
                ('pays_residence', models.CharField(blank=True, help_text='Country of residence.', max_length=100, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text="Patient's biological sex.", max_length=1)),
                ('langue_parlee', models.CharField(blank=True, help_text='Language primarily spoken by the patient.', max_length=50, null=True)),
                ('ville', models.CharField(blank=True, help_text='City of residence.', max_length=100, null=True)),
                ('quartier', models.CharField(blank=True, help_text='Neighborhood or district of residence.', max_length=100, null=True)),
                ('poids', models.FloatField(blank=True, help_text="Patient's weight in kilograms.", null=True)),
                ('taille', models.FloatField(blank=True, help_text="Patient's height in meters.", null=True)),
                ('maladie_courante', models.TextField(blank=True, help_text='Any current medical conditions or symptoms.', null=True)),
                ('maladie_familiale', models.TextField(blank=True, help_text='Any family history of diseases or conditions.', null=True)),
                ('last_update', models.DateTimeField(auto_now=True, help_text="Date and time of the last update to the patient's profile.")),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date and time the patient's profile was created.")),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
