# Generated by Django 5.2.1 on 2025-06-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['nom'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prenom',
        ),
    ]
