# Generated by Django 5.2.2 on 2025-06-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordonnance', models.CharField(blank=True, help_text='Unique identifier for the prescription.', max_length=100, null=True, unique=True)),
                ('libelle', models.CharField(help_text='General title or description of the prescription.', max_length=255)),
                ('date_emission', models.DateField(auto_now_add=True, help_text='Date when the prescription was issued.')),
                ('duree_traitement', models.CharField(blank=True, help_text="Duration of the treatment (e.g., '7 jours', '1 mois').", max_length=100, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Date and time of the last update to the prescription record.')),
                ('consultation', models.ForeignKey(help_text='The consultation during which this prescription was issued.', on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='Consultations.consultation')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_prescription', models.CharField(blank=True, help_text='Unique identifier for this specific medication prescription.', max_length=100, null=True, unique=True)),
                ('libelle', models.CharField(help_text='Name of the medication or treatment.', max_length=255)),
                ('dosage', models.CharField(help_text="Dosage of the medication (e.g., '500mg', '2ml').", max_length=100)),
                ('frequence', models.CharField(help_text="Frequency of administration (e.g., '2 fois par jour', 'chaque matin').", max_length=100)),
                ('periode_de_prise', models.CharField(blank=True, help_text="Period or duration for taking the medication (e.g., 'avant les repas', 'au coucher').", max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or instructions for this prescription.', null=True)),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Date and time of the last update to this prescription.')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date and time this prescription was created.')),
                ('ordonnance', models.ForeignKey(help_text='The main prescription containing this specific medication order.', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='Prescriptions.ordonnance')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['ordonnance__numero_ordonnance', 'libelle'],
            },
        ),
    ]
